{% set version = '1.27.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hexbin
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/hexbin_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/hexbin/hexbin_{{ version }}.tar.gz
  sha256: 46d47b1efef75d6f126af686a4dd614228b60418b9a5bde9e9e5d11200a0ee52

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: marray, affy, Biobase, limma
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-lattice

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-lattice

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('hexbin')"           # [not win]
    - "\"%R%\" -e \"library('hexbin')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://github.com/edzer/hexbin
  license: GPL-2
  summary: Binning and plotting functions for hexagonal bins.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: hexbin
# Version: 1.27.2
# Title: Hexagonal Binning Routines
# Author: Dan Carr <dcarr@voxel.galaxy.gmu.edu>, ported by Nicholas Lewin-Koh and Martin Maechler <maechler@stat.math.ethz.ch>, contains copies of lattice functions written by Deepayan Sarkar  <deepayan.sarkar@r-project.org>
# Maintainer: Edzer Pebesma <edzer.pebesma@uni-muenster.de>
# Depends: R (>= 2.0.1), methods
# Imports: lattice, grid, graphics, grDevices, stats, utils
# Suggests: marray, affy, Biobase, limma
# Description: Binning and plotting functions for hexagonal bins.
# Collate: lattice.R BTC.R BTY.R grid.hexagons.R grid.hexlegend.R hbox.R hdiffplot.R hexbinList.R hexbinplot.R hexbin.s4.R hexpanel.R hexplom.R hexPlotMA.R hexutil.R hexViewport.R HO.R LINGRAY.R LOCS.R MAG.R RB.R smoothHexbin.R
# License: GPL-2
# NeedsCompilation: yes
# URL: http://github.com/edzer/hexbin
# Packaged: 2018-01-15 16:56:46 UTC; edzer
# Repository: CRAN
# Date/Publication: 2018-01-15 18:56:40 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
