travis:
  secure:
    BINSTAR_TOKEN: LCJNB1ZJDP9aD3PSAxTIPDkZE+JLwGjoukL0lKoZnF2C2mBQ8nMrWbL4vsr0nLrKVFIsqs6YETRkMCGFIbZJTpJ4kaLOqqlhhVMxTJECql6+r13KAvslqkytaGY703bxsOWWOZr+S4NK36HxccM+jSomB/8EDLaNFo3VLc5FvDEGz3KgY4vKX8sCwnhLG2hZJzalZ/GplBvtGbtacUm/J2KhJUjtVxvk1pALf50z2j4X8K79ySyhsTPkAtzEJLB1auSJWjwW5ANfT4CFcquVIv7dFMQ5ibMd2iyUJlTAFuDzWhCs9shmayruf10uyxNFe+jXcBta4i7k/U2B55Z6xUC/CsUvUm84LUqp8aZX3jzf3/zV3/IZb55ykKHPtg8lOax1RDL2Yb2hPlqQ5aG0FUhoURXc75SRMpuByPaSTVw5GPTKANew9gNZeDdzmnMQ/Ryq5iE0DIHrnZKQVxQ+LtTRH17cTS9XxhRxgXVv6088lReYiJZsIQY550Pb7SowcaPGZPlJTYcIzGsvM8AXzHYbYKPCPhJIZRSwwpTco9i2tAZ0SGJqLT4w8YbMlzGxoPZnBiFOS6tPX+dVGstbGNHDwikOaI4H01lRocIWREqsITRgoNSWwTm3H2qt5YJX3hiuni5rDbSY50YJ2QILp2Dj7X12lXvTbcosLpCgDcg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
